# Generated by Django 3.2.15 on 2022-11-01 02:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_receta', models.CharField(max_length=100)),
                ('descripcion_receta', models.CharField(max_length=240)),
                ('receta', ckeditor.fields.RichTextField()),
                ('autor_usuario', models.CharField(max_length=100)),
                ('autor_nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Recetas/')),
            ],
        ),
    ]
