# Generated by Django 3.2.15 on 2022-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='autor_nombre',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='autor_usuario',
        ),
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
