# Generated by Django 3.2.15 on 2022-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_receta_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion_receta',
            field=models.CharField(default='', max_length=240),
        ),
    ]
