# Generated by Django 3.2.15 on 2022-10-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_receta_descripcion_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion_receta',
            field=models.CharField(max_length=240),
        ),
    ]
