# Generated by Django 3.2.15 on 2022-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('emisor', models.CharField(max_length=100)),
                ('receptor', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=1000)),
                ('leido', models.BooleanField()),
            ],
        ),
    ]
