# Generated by Django 3.2.15 on 2022-10-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='cuerpo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
