# Generated by Django 4.1 on 2022-11-02 02:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0002_auto_20221011_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
